# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Rlist
version:      1.43
version_from: lib/Data/Rlist.pm
installdirs:  site
requires:
    B::Deparse:                    0
    Benchmark:                     0
    MIME::Base64:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
